<?php

########################################################################
# Extension Manager/Repository config file for ext: "bb_shreknet"
#
# Auto generated by Extension Builder 2011-06-14
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Vampire the Masquerade: Shreknet',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Bastian Bringenberg',
	'author_email' => 'spam@bastian-bringenberg.de',
	'author_company' => 'Bastian Bringenberg',
	'shy' => '',
	'dependencies' => 'cms,extbase,fluid',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.3.0',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>